/**
 * ExpressionManager for TARA
 * Ensures every single expression produces distinct, visible changes across:
 * - Eye shape & arc
 * - Pupil offset, size, and geometry
 * - Eyebrow curvature & tilt
 * - Mouth shape & curvature
 * - Accents (blush, sweat drop, tears, dizzy spiral, hearts, sparkles)
 */

import { ExpressionConfig, TaraExpression, TaraEyeState, TaraMouthState } from '../types';

export const EXPRESSION_DEFINITIONS: Record<TaraExpression, ExpressionConfig> = {
  happy: {
    name: 'happy',
    label: 'Happy',
    eyeState: 'normal',
    mouthState: 'SMILE',
    pupilOffsetX: 0,
    pupilOffsetY: -0.1,
    pupilScale: 1.05,
    eyebrowAngle: -5,
    eyebrowOffset: -2,
    blush: true,
    blushIntensity: 0.5,
    eyelidCurve: 0.4,
    description: 'Bright gentle curved eyes with a warm crescent smile and soft cheeks.',
  },
  big_smile: {
    name: 'big_smile',
    label: 'Big Smile',
    eyeState: 'normal',
    mouthState: 'OPEN_MEDIUM',
    pupilOffsetX: 0,
    pupilOffsetY: -0.15,
    pupilScale: 1.15,
    eyebrowAngle: -8,
    eyebrowOffset: -4,
    blush: true,
    blushIntensity: 0.7,
    sparkle: true,
    eyelidCurve: 0.6,
    description: 'Enthusiastic sparkling eyes with high brows and broad open toothy smile.',
  },
  laughing: {
    name: 'laughing',
    label: 'Laughing',
    eyeState: 'closed',
    mouthState: 'LAUGHING',
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilScale: 1.0,
    eyebrowAngle: -10,
    eyebrowOffset: -5,
    blush: true,
    blushIntensity: 0.8,
    eyelidCurve: 0.8,
    description: 'Eyes squeezed shut into happy upward arcs, wide bouncing laugh mouth.',
  },
  giggling: {
    name: 'giggling',
    label: 'Giggling',
    eyeState: 'squint',
    mouthState: 'OPEN_SMALL',
    pupilOffsetX: 0.1,
    pupilOffsetY: -0.1,
    pupilScale: 0.95,
    eyebrowAngle: -6,
    eyebrowOffset: -3,
    blush: true,
    blushIntensity: 0.75,
    eyelidCurve: 0.7,
    description: 'Squinted playful eyes with trembling cheeks and small cute laugh mouth.',
  },
  excited: {
    name: 'excited',
    label: 'Excited',
    eyeState: 'sparkle',
    mouthState: 'OPEN_WIDE',
    pupilOffsetX: 0,
    pupilOffsetY: -0.1,
    pupilScale: 1.3,
    eyebrowAngle: -12,
    eyebrowOffset: -6,
    blush: true,
    blushIntensity: 0.7,
    sparkle: true,
    eyelidCurve: 0.3,
    description: 'Stars/sparkles in pupils, elevated high arched brows, open enthusiastic mouth.',
  },
  curious: {
    name: 'curious',
    label: 'Curious',
    eyeState: 'wide',
    mouthState: 'O_SHAPE',
    pupilOffsetX: 0.25,
    pupilOffsetY: -0.2,
    pupilScale: 1.1,
    eyebrowAngle: 10,
    eyebrowOffset: -3,
    blush: false,
    blushIntensity: 0,
    eyelidCurve: 0.1,
    description: 'One raised eyebrow, dilated pupils glancing to the upper right, intrigued small O-mouth.',
  },
  confused: {
    name: 'confused',
    label: 'Confused',
    eyeState: 'normal',
    mouthState: 'SMALL',
    pupilOffsetX: -0.2,
    pupilOffsetY: 0.15,
    pupilScale: 0.9,
    eyebrowAngle: 18,
    eyebrowOffset: 0,
    blush: false,
    blushIntensity: 0,
    sweatDrop: true,
    eyelidCurve: -0.2,
    description: 'Asymmetric tilted eyebrows with uneven pupils, crooked small mouth, sweat drop.',
  },
  surprised: {
    name: 'surprised',
    label: 'Surprised',
    eyeState: 'wide',
    mouthState: 'O_SHAPE',
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilScale: 0.85,
    eyebrowAngle: -14,
    eyebrowOffset: -7,
    blush: false,
    blushIntensity: 0,
    eyelidCurve: 0,
    description: 'Huge rounded eyes with contracted small center pupils and deep vertical O-mouth.',
  },
  sad: {
    name: 'sad',
    label: 'Sad',
    eyeState: 'half_closed',
    mouthState: 'SMALL',
    pupilOffsetX: 0,
    pupilOffsetY: 0.25,
    pupilScale: 0.9,
    eyebrowAngle: 15,
    eyebrowOffset: 3,
    blush: false,
    blushIntensity: 0,
    tears: true,
    eyelidCurve: -0.5,
    description: 'Drooping downward eyelids, sad angled brows, downturned trembling mouth, tears.',
  },
  angry: {
    name: 'angry',
    label: 'Angry',
    eyeState: 'squint',
    mouthState: 'OPEN_MEDIUM',
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilScale: 0.8,
    eyebrowAngle: -22,
    eyebrowOffset: 4,
    blush: false,
    blushIntensity: 0,
    eyelidCurve: -0.6,
    description: 'Sharply furrowed downward slant eyebrows, narrowed focused pupils, sharp grit mouth.',
  },
  sleepy: {
    name: 'sleepy',
    label: 'Sleepy',
    eyeState: 'half_closed',
    mouthState: 'SMALL',
    pupilOffsetX: 0,
    pupilOffsetY: 0.1,
    pupilScale: 0.85,
    eyebrowAngle: 2,
    eyebrowOffset: 2,
    blush: false,
    blushIntensity: 0.1,
    eyelidCurve: -0.4,
    description: 'Heavy drooping eyelids nearly closing, small yawning mouth, relaxed eyebrows.',
  },
  deep_sleep: {
    name: 'deep_sleep',
    label: 'Deep Sleep',
    eyeState: 'closed',
    mouthState: 'CLOSED',
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilScale: 0.8,
    eyebrowAngle: 0,
    eyebrowOffset: 3,
    blush: false,
    blushIntensity: 0.2,
    eyelidCurve: -0.2,
    description: 'Fully peaceful closed curved line eyes, gentle breathing mouth, calm resting face.',
  },
  shy: {
    name: 'shy',
    label: 'Shy',
    eyeState: 'normal',
    mouthState: 'SMILE',
    pupilOffsetX: -0.3,
    pupilOffsetY: 0.25,
    pupilScale: 0.95,
    eyebrowAngle: 8,
    eyebrowOffset: 1,
    blush: true,
    blushIntensity: 0.9,
    eyelidCurve: 0.2,
    description: 'Pupils averted downward-left, deep rosy blush lines, sweet timid curved smile.',
  },
  embarrassed: {
    name: 'embarrassed',
    label: 'Embarrassed',
    eyeState: 'squint',
    mouthState: 'SMALL',
    pupilOffsetX: 0.2,
    pupilOffsetY: 0.2,
    pupilScale: 0.9,
    eyebrowAngle: 12,
    eyebrowOffset: 2,
    blush: true,
    blushIntensity: 1.0,
    sweatDrop: true,
    eyelidCurve: 0.1,
    description: 'Max blush intensity across cheeks, sweat drop on temple, wavy embarrassed mouth.',
  },
  blushing: {
    name: 'blushing',
    label: 'Blushing',
    eyeState: 'hearts',
    mouthState: 'SMILE',
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilScale: 1.1,
    eyebrowAngle: -6,
    eyebrowOffset: -2,
    blush: true,
    blushIntensity: 0.95,
    hearts: true,
    eyelidCurve: 0.5,
    description: 'Heart-shaped pupil highlights, glowing blushing cheeks, affectionate smile.',
  },
  scared: {
    name: 'scared',
    label: 'Scared',
    eyeState: 'wide',
    mouthState: 'OPEN_SMALL',
    pupilOffsetX: 0,
    pupilOffsetY: -0.1,
    pupilScale: 0.6,
    eyebrowAngle: 20,
    eyebrowOffset: -5,
    blush: false,
    blushIntensity: 0,
    sweatDrop: true,
    eyelidCurve: -0.3,
    description: 'Pin-point shrunken pupils shivering, high arching frightened brows, jittery open mouth.',
  },
  worried: {
    name: 'worried',
    label: 'Worried',
    eyeState: 'normal',
    mouthState: 'SMALL',
    pupilOffsetX: 0,
    pupilOffsetY: -0.1,
    pupilScale: 0.9,
    eyebrowAngle: 16,
    eyebrowOffset: -1,
    blush: false,
    blushIntensity: 0,
    sweatDrop: true,
    eyelidCurve: -0.3,
    description: 'Brows tilted inward high at center, anxious wavy mouth, subtle sweat drop.',
  },
  suspicious: {
    name: 'suspicious',
    label: 'Suspicious',
    eyeState: 'squint',
    mouthState: 'SMALL',
    pupilOffsetX: 0.4,
    pupilOffsetY: 0,
    pupilScale: 0.85,
    eyebrowAngle: -10,
    eyebrowOffset: 2,
    blush: false,
    blushIntensity: 0,
    eyelidCurve: -0.4,
    description: 'Narrow slits squinting, pupils hard-locked to side edge, skeptical straight-line mouth.',
  },
  dizzy: {
    name: 'dizzy',
    label: 'Dizzy',
    eyeState: 'dizzy_spiral',
    mouthState: 'O_SHAPE',
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilScale: 1.0,
    eyebrowAngle: 5,
    eyebrowOffset: 0,
    blush: false,
    blushIntensity: 0.3,
    dizzySpiral: true,
    eyelidCurve: 0,
    description: 'Swirling animated concentric spiral eyes, wobbling loopy circle mouth.',
  },
  focused: {
    name: 'focused',
    label: 'Focused',
    eyeState: 'squint',
    mouthState: 'CLOSED',
    pupilOffsetX: 0,
    pupilOffsetY: 0.15,
    pupilScale: 1.0,
    eyebrowAngle: -14,
    eyebrowOffset: 1,
    blush: false,
    blushIntensity: 0,
    eyelidCurve: -0.2,
    description: 'Sharp level brow determination, narrowed intense pupils angled toward task, firm line mouth.',
  },
  thinking: {
    name: 'thinking',
    label: 'Thinking',
    eyeState: 'look_up',
    mouthState: 'SMALL',
    pupilOffsetX: 0.35,
    pupilOffsetY: -0.4,
    pupilScale: 0.95,
    eyebrowAngle: 10,
    eyebrowOffset: -2,
    blush: false,
    blushIntensity: 0,
    eyelidCurve: 0.1,
    description: 'Pupils cast upward to corner pondering, one brow raised, thoughtful pursed mouth.',
  },
  amazed: {
    name: 'amazed',
    label: 'Amazed',
    eyeState: 'sparkle',
    mouthState: 'O_SHAPE',
    pupilOffsetX: 0,
    pupilOffsetY: -0.1,
    pupilScale: 1.25,
    eyebrowAngle: -12,
    eyebrowOffset: -5,
    blush: true,
    blushIntensity: 0.6,
    sparkle: true,
    eyelidCurve: 0.4,
    description: 'Large star-lit glowing eyes reflecting wonder, elevated high brows, round breath-taken mouth.',
  },
  proud: {
    name: 'proud',
    label: 'Proud',
    eyeState: 'normal',
    mouthState: 'SMILE',
    pupilOffsetX: 0,
    pupilOffsetY: -0.2,
    pupilScale: 1.0,
    eyebrowAngle: -8,
    eyebrowOffset: -3,
    blush: true,
    blushIntensity: 0.6,
    eyelidCurve: 0.5,
    description: 'Confident upturned chin look, eyes slightly lowered satisfaction, self-assured smirk.',
  },
  bored: {
    name: 'bored',
    label: 'Bored',
    eyeState: 'half_closed',
    mouthState: 'CLOSED',
    pupilOffsetX: 0.2,
    pupilOffsetY: 0.3,
    pupilScale: 0.9,
    eyebrowAngle: 0,
    eyebrowOffset: 3,
    blush: false,
    blushIntensity: 0,
    eyelidCurve: -0.3,
    description: 'Half-shut flat eyelids, pupils sluggishly drifting off-center, neutral uninspired flat line mouth.',
  },
  playful: {
    name: 'playful',
    label: 'Playful',
    eyeState: 'wink',
    mouthState: 'OPEN_SMALL',
    pupilOffsetX: 0,
    pupilOffsetY: -0.1,
    pupilScale: 1.05,
    eyebrowAngle: -8,
    eyebrowOffset: -3,
    blush: true,
    blushIntensity: 0.65,
    eyelidCurve: 0.6,
    description: 'Cheeky one-eye wink with bright open other eye, lively cheerful open grin.',
  },
  teasing: {
    name: 'teasing',
    label: 'Teasing',
    eyeState: 'wink',
    mouthState: 'SMILE',
    pupilOffsetX: 0.2,
    pupilOffsetY: 0,
    pupilScale: 1.0,
    eyebrowAngle: -10,
    eyebrowOffset: -2,
    blush: true,
    blushIntensity: 0.6,
    eyelidCurve: 0.5,
    description: 'Sly wink with sideways pupil glance and playful tongue-tip/asymmetric smirk.',
  },
  wink: {
    name: 'wink',
    label: 'Wink',
    eyeState: 'wink',
    mouthState: 'SMILE',
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilScale: 1.1,
    eyebrowAngle: -6,
    eyebrowOffset: -3,
    blush: true,
    blushIntensity: 0.55,
    eyelidCurve: 0.5,
    description: 'Crisp deliberate wink on right eye, open smiling left eye with cute blush.',
  },
  listening: {
    name: 'listening',
    label: 'Listening',
    eyeState: 'normal',
    mouthState: 'CLOSED',
    pupilOffsetX: 0,
    pupilOffsetY: -0.05,
    pupilScale: 1.1,
    eyebrowAngle: -5,
    eyebrowOffset: -3,
    blush: false,
    blushIntensity: 0.2,
    eyelidCurve: 0.3,
    description: 'Attentive widened eyes locked forward, gentle receptive closed mouth, listening pose.',
  },
  speaking: {
    name: 'speaking',
    label: 'Speaking',
    eyeState: 'normal',
    mouthState: 'SPEAKING',
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilScale: 1.0,
    eyebrowAngle: -4,
    eyebrowOffset: -2,
    blush: false,
    blushIntensity: 0.2,
    eyelidCurve: 0.2,
    description: 'Active expressive pupils with animated vocalizing mouth opening and closing naturally.',
  },
  singing: {
    name: 'singing',
    label: 'Singing',
    eyeState: 'closed',
    mouthState: 'SINGING',
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilScale: 1.05,
    eyebrowAngle: -10,
    eyebrowOffset: -4,
    blush: true,
    blushIntensity: 0.65,
    eyelidCurve: 0.7,
    description: 'Soulful closed happy arc eyes, rhythmically shaped singing mouth (O to A shape).',
  },
  celebrating: {
    name: 'celebrating',
    label: 'Celebrating',
    eyeState: 'sparkle',
    mouthState: 'OPEN_WIDE',
    pupilOffsetX: 0,
    pupilOffsetY: -0.15,
    pupilScale: 1.3,
    eyebrowAngle: -15,
    eyebrowOffset: -6,
    blush: true,
    blushIntensity: 0.8,
    sparkle: true,
    eyelidCurve: 0.7,
    description: 'Maximum joy sparkles in eyes, joyful high brows, triumphant wide open smile.',
  },
  disappointed: {
    name: 'disappointed',
    label: 'Disappointed',
    eyeState: 'half_closed',
    mouthState: 'SMALL',
    pupilOffsetX: 0,
    pupilOffsetY: 0.2,
    pupilScale: 0.85,
    eyebrowAngle: 12,
    eyebrowOffset: 3,
    blush: false,
    blushIntensity: 0,
    sweatDrop: true,
    eyelidCurve: -0.4,
    description: 'Slumping eyelids, flat disheartened brow line, tiny downturned unhappy mouth line.',
  },
  frustrated: {
    name: 'frustrated',
    label: 'Frustrated',
    eyeState: 'squint',
    mouthState: 'OPEN_SMALL',
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilScale: 0.8,
    eyebrowAngle: -18,
    eyebrowOffset: 3,
    blush: false,
    blushIntensity: 0,
    sweatDrop: true,
    eyelidCurve: -0.5,
    description: 'Tightly squeezed squint eyes, harsh angled frown brows, strained open grit mouth.',
  },
  tired: {
    name: 'tired',
    label: 'Tired',
    eyeState: 'half_closed',
    mouthState: 'SMALL',
    pupilOffsetX: 0,
    pupilOffsetY: 0.25,
    pupilScale: 0.85,
    eyebrowAngle: 6,
    eyebrowOffset: 3,
    blush: false,
    blushIntensity: 0.1,
    eyelidCurve: -0.4,
    description: 'Heavy drooping lower-eyelid bags, eyes barely half open, exhausted gentle sigh mouth.',
  },
  neutral: {
    name: 'neutral',
    label: 'Neutral',
    eyeState: 'normal',
    mouthState: 'CLOSED',
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilScale: 1.0,
    eyebrowAngle: 0,
    eyebrowOffset: 0,
    blush: false,
    blushIntensity: 0,
    eyelidCurve: 0,
    description: 'Clean balanced resting desktop companion eyes, calm closed mouth.',
  },
};

export class ExpressionManager {
  private currentExpression: TaraExpression = 'neutral';
  private targetExpression: TaraExpression = 'neutral';
  private transitionProgress: number = 1.0;

  public getExpression(): TaraExpression {
    return this.currentExpression;
  }

  public setExpression(exp: TaraExpression): void {
    if (EXPRESSION_DEFINITIONS[exp]) {
      this.currentExpression = exp;
      this.targetExpression = exp;
      this.transitionProgress = 1.0;
    }
  }

  public getConfig(exp?: TaraExpression): ExpressionConfig {
    const key = exp || this.currentExpression;
    return EXPRESSION_DEFINITIONS[key] || EXPRESSION_DEFINITIONS.neutral;
  }

  public getAllExpressions(): ExpressionConfig[] {
    return Object.values(EXPRESSION_DEFINITIONS);
  }
}

export const expressionManager = new ExpressionManager();
