import React, { useState } from 'react';
import { Upload, CheckCircle2, AlertTriangle, ShieldCheck, RefreshCw, HardDrive } from 'lucide-react';

interface TabOTAProps {
  currentVersion: string;
}

export const TabOTA: React.FC<TabOTAProps> = ({ currentVersion }) => {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [isFlashing, setIsFlashing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [statusMsg, setStatusMsg] = useState<string | null>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setSelectedFile(file);
      setStatusMsg(`Selected binary: ${file.name} (${Math.round(file.size / 1024)} KB)`);
    }
  };

  const handleStartOTA = () => {
    if (!selectedFile) return;
    setIsFlashing(true);
    setProgress(0);
    setStatusMsg('Initiating OTA update stream with ESP32 flash memory...');

    const interval = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          clearInterval(interval);
          setIsFlashing(false);
          setStatusMsg('Firmware flashed successfully! ESP32 is verifying MD5 checksum and rebooting into new partition...');
          return 100;
        }
        return prev + 10;
      });
    }, 400);
  };

  return (
    <div className="space-y-6">
      {/* Overview Banner */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5">
        <h3 className="text-sm font-bold text-slate-200 mb-2 flex items-center gap-2">
          <Upload className="w-4 h-4 text-cyan-400" />
          Standard ESP32 Over-The-Air (OTA) Update System
        </h3>
        <p className="text-[12px] text-slate-400 mb-3">
          TARA features a fail-safe OTA architecture managed by <code className="text-cyan-400 font-mono">OTAManager</code>.
          Using dual 1.9MB application partitions (`app0` and `app1`), the new firmware is flashed while the active partition continues running. If flashing fails, TARA boots safely back into the existing partition.
        </p>
        <div className="flex items-center gap-4 text-xs font-mono text-slate-300">
          <span>Active Firmware: <span className="text-cyan-400 font-bold">v{currentVersion}</span></span>
          <span>Target Platform: <span className="text-emerald-400 font-bold">ESP32 Xtensa Dual-Core</span></span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Upload Column */}
        <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-4">
          <h4 className="text-sm font-bold text-slate-200">Upload Compiled Firmware Binary</h4>
          <p className="text-[12px] text-slate-400">
            Upload the compiled <code className="text-cyan-400 font-mono">firmware.bin</code> generated by Arduino IDE or PlatformIO.
          </p>

          <div className="border-2 border-dashed border-slate-800 hover:border-cyan-500 rounded-xl p-6 text-center transition-all bg-slate-950/60">
            <input
              type="file"
              accept=".bin"
              id="ota-file"
              onChange={handleFileChange}
              disabled={isFlashing}
              className="hidden"
            />
            <label htmlFor="ota-file" className="cursor-pointer block space-y-2">
              <Upload className="w-8 h-8 text-cyan-400 mx-auto" />
              <div className="text-xs font-semibold text-slate-200">
                {selectedFile ? selectedFile.name : 'Click to select .bin firmware file'}
              </div>
              <div className="text-[11px] text-slate-500">
                Standard ESP32 flash image (Max 1,966,080 bytes)
              </div>
            </label>
          </div>

          {selectedFile && (
            <button
              onClick={handleStartOTA}
              disabled={isFlashing}
              className="w-full bg-cyan-500 hover:bg-cyan-400 disabled:opacity-50 text-slate-950 font-bold py-2.5 px-4 rounded-lg text-xs transition-all flex items-center justify-center gap-2 shadow-lg shadow-cyan-500/20"
            >
              {isFlashing ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  Flashing Firmware ({progress}%)...
                </>
              ) : (
                <>
                  <Upload className="w-4 h-4" />
                  Flash Firmware to Inactive Slot
                </>
              )}
            </button>
          )}

          {/* Flashing Progress Bar */}
          {isFlashing && (
            <div className="space-y-1.5 pt-2">
              <div className="flex justify-between text-xs font-mono">
                <span className="text-slate-400">Flashing Progress</span>
                <span className="text-cyan-400 font-bold">{progress}%</span>
              </div>
              <div className="w-full h-2.5 bg-slate-950 rounded-full overflow-hidden border border-slate-800">
                <div
                  className="h-full bg-cyan-400 transition-all duration-300"
                  style={{ width: `${progress}%` }}
                ></div>
              </div>
            </div>
          )}

          {statusMsg && (
            <div className="p-3 rounded-lg bg-slate-950 border border-slate-800 font-mono text-xs text-cyan-300 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-cyan-400 shrink-0" />
              <span>{statusMsg}</span>
            </div>
          )}
        </div>

        {/* Safety & Integrity Column */}
        <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-4">
          <h4 className="text-sm font-bold text-slate-200 flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            Dual-Bank Fail-Safe Protection
          </h4>

          <div className="space-y-3 text-xs text-slate-300">
            <div className="p-3 bg-slate-950 rounded-lg border border-slate-800 flex items-start gap-2.5">
              <div className="w-2 h-2 rounded-full bg-emerald-400 mt-1 shrink-0"></div>
              <div>
                <span className="font-bold text-slate-100">Rollback Safety Guard:</span> If the new firmware crashes during initial startup, the ESP32 hardware watchdog triggers an automatic rollback to the previous working slot.
              </div>
            </div>

            <div className="p-3 bg-slate-950 rounded-lg border border-slate-800 flex items-start gap-2.5">
              <div className="w-2 h-2 rounded-full bg-cyan-400 mt-1 shrink-0"></div>
              <div>
                <span className="font-bold text-slate-100">MD5 Checksum Verification:</span> Every flash block verifies cryptographic hash integrity before committing the boot pointer in <code className="text-cyan-400 font-mono">otadata</code>.
              </div>
            </div>

            <div className="p-3 bg-slate-950 rounded-lg border border-slate-800 flex items-start gap-2.5">
              <div className="w-2 h-2 rounded-full bg-amber-400 mt-1 shrink-0"></div>
              <div>
                <span className="font-bold text-slate-100">Non-Volatile Persistence:</span> Wi-Fi credentials, robot personality, and AI API keys stored in <code className="text-cyan-400 font-mono">nvs</code> are completely preserved during OTA upgrades.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
